# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .resource import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_twingate.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_twingate.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "twingate",
  "mod": "index/resource",
  "fqn": "pulumi_twingate",
  "classes": {
   "twingate:index/resource:Resource": "Resource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "twingate",
  "token": "pulumi:providers:twingate",
  "fqn": "pulumi_twingate",
  "class": "Provider"
 }
]
"""
)
