// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Outputs
{

    [OutputType]
    public sealed class ResourceProtocolsUdp
    {
        public readonly string Policy;
        public readonly ImmutableArray<string> Ports;

        [OutputConstructor]
        private ResourceProtocolsUdp(
            string policy,

            ImmutableArray<string> ports)
        {
            Policy = policy;
            Ports = ports;
        }
    }
}
