// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Outputs
{

    [OutputType]
    public sealed class ResourceProtocols
    {
        /// <summary>
        /// Whether to allow ICMP (ping) traffic
        /// </summary>
        public readonly bool? AllowIcmp;
        public readonly Outputs.ResourceProtocolsTcp Tcp;
        public readonly Outputs.ResourceProtocolsUdp Udp;

        [OutputConstructor]
        private ResourceProtocols(
            bool? allowIcmp,

            Outputs.ResourceProtocolsTcp tcp,

            Outputs.ResourceProtocolsUdp udp)
        {
            AllowIcmp = allowIcmp;
            Tcp = tcp;
            Udp = udp;
        }
    }
}
