// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Inputs
{

    public sealed class ResourceAccessGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("groupIds")]
        private InputList<string>? _groupIds;
        public InputList<string> GroupIds
        {
            get => _groupIds ?? (_groupIds = new InputList<string>());
            set => _groupIds = value;
        }

        [Input("serviceAccountIds")]
        private InputList<string>? _serviceAccountIds;
        public InputList<string> ServiceAccountIds
        {
            get => _serviceAccountIds ?? (_serviceAccountIds = new InputList<string>());
            set => _serviceAccountIds = value;
        }

        public ResourceAccessGetArgs()
        {
        }
        public static new ResourceAccessGetArgs Empty => new ResourceAccessGetArgs();
    }
}
