// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Twingate.Inputs
{

    public sealed class ResourceProtocolsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to allow ICMP (ping) traffic
        /// </summary>
        [Input("allowIcmp")]
        public Input<bool>? AllowIcmp { get; set; }

        [Input("tcp", required: true)]
        public Input<Inputs.ResourceProtocolsTcpGetArgs> Tcp { get; set; } = null!;

        [Input("udp", required: true)]
        public Input<Inputs.ResourceProtocolsUdpGetArgs> Udp { get; set; } = null!;

        public ResourceProtocolsGetArgs()
        {
        }
        public static new ResourceProtocolsGetArgs Empty => new ResourceProtocolsGetArgs();
    }
}
