name: Upgrade provider
on:
  pull_request:
    paths-ignore:
      - docs
      - .devcontainer
      - examples
  # workflow_dispatch: {}
# on:
#   issues:
#     types:
#     - opened
#   schedule:
#     - cron: '0 5 * * *'

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@main
      with:
        kind: all
        email: $(git --no-pager log --format=format:'%ae' -n 1)
        username: $(git --no-pager log --format=format:'%an' -n 1)
      env:
        #GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

